FROM node:18-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json .
COPY server ./server
COPY public ./public
RUN npm install

ENV NODE_ENV production
ENV PORT 3000

ENV VAR_COLLECTION_NAME=${COLLECTION_NAME}
ENV VAR_DB_NAME=${DB_NAME}
ENV VAR_DB_PREFIX=${DB_PREFIX}
ENV VAR_DB_USERNAME=${DB_USERNAME}
ENV VAR_DB_PASSWORD=${DB_PASSWORD}
ENV VAR_DB_HOSTNAME=${DB_HOSTNAME}
ENV VAR_REDIS_URI=${REDIS_URI}
ENV VAR_REDIS_PORT=${REDIS_PORT}

ENV COLLECTION_NAME $VAR_COLLECTION_NAME
ENV DB_NAME $VAR_DB_NAME
ENV DB_PREFIX $VAR_DB_PREFIX
ENV DB_USERNAME $VAR_DB_USERNAME
ENV DB_PASSWORD $VAR_DB_PASSWORD
ENV DB_HOSTNAME $VAR_DB_HOSTNAME
ENV REDIS_URI $VAR_REDIS_URI
ENV REDIS_PORT $VAR_REDIS_PORT

EXPOSE 3000

CMD ["npm", "start"]
