FROM node:18-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json .
COPY server ./server
COPY public ./public
RUN npm install

ENV NODE_ENV production
ENV PORT 3000
ENV COLLECTION_NAME=${COLLECTION_NAME}
ENV DB_NAME=${DB_NAME}
ENV DB_PREFIX=${DB_PREFIX}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOSTNAME=${DB_HOSTNAME}
ENV REDIS_URI=${REDIS_URI}
ENV REDIS_PORT=${REDIS_PORT}

EXPOSE 3000

CMD ["npm", "start"]
